### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by partymike** [corbinmunce/domoticz-plex-webhook#1]
Thanks for this, when you say run the script - node main.js would you run from the command line or create a service? 

Pretty new to this and was looking at a script in domoticz but your way seems to be a much improved method.

Any help appreciated :-)

**Comment by corbinmunce** [comment]
Make sure you have installed Node.js first, then run from the command as 'node main.js'

Once working, you could create a service - which is what I did on my Domoticz server, put it in /etc/init.d

So far it has been working 100% with immediate updates into Domoticz.

**Comment by partymike** [comment]
thanks for that, if it helps anyone else I created a system service to run the script:
------
[Unit]
Description=Plex Webhook
After=multi-user.target

[Service]
Type=simple
ExecStart=/usr/bin/node /home/pi/domoticz-plex-webhook/main.js
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
-------
